
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Les commandes Prisma CLI (migrate, db push, studio) doivent passer par la
    // connexion DIRECTE (Supabase session pooler, port 5432), et surtout PAS par
    // le pooler transactionnel (pgbouncer, port 6543) qui fait échouer les
    // migrations (« prepared statement "s1" already exists »). L'application, elle,
    // continue d'utiliser DATABASE_URL (pooler 6543) via prisma/schema.prisma.
    url: env("DIRECT_URL"),
  },
});
