
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `DATABASE_URL` est la variable canonique (prod, dev via backend/.env). En CI,
// seule la base de test isolée est fournie via `TEST_DATABASE_URL` (voir
// .github/workflows/backend-ci.yml + vitest.globalSetup.ts) et aucun `.env`
// n'existe : on retombe donc dessus pour que `prisma generate` (qui ne se
// connecte pas) charge la config sans exiger `DATABASE_URL`. `env("DATABASE_URL")`
// levait ici un `PrismaConfigEnvError` au chargement, cassant la CI backend.
const datasourceUrl =
  process.env.DATABASE_URL ?? process.env.TEST_DATABASE_URL ?? "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: datasourceUrl,
  },
});
