import PDFDocument from 'pdfkit'
import type { WalletMovement, WalletMovementType } from '~~/server/utils/walletStore'
import type { Payment } from '~~/server/utils/paymentStore'
import type { PlanSlug } from '~~/app/data/plans'
import type { User } from '~~/server/utils/userStore'

/**
 * Génération de reçus PDF (#363) pour les débits/libérations de séquestre et
 * les paiements d'abonnement. Document interne simple (pas une facture
 * fiscale) — juste assez d'information pour que chercheur/prestataire
 * conservent une trace de chaque mouvement d'argent.
 *
 * Pas d'instance vue-i18n côté serveur : les libellés du PDF sont donc un
 * petit dictionnaire dédié (FR/EN) plutôt que les fichiers i18n/locales/*,
 * sélectionné via un paramètre de requête `?locale=` fourni par l'appelant
 * (le composant client connaît déjà `useI18n().locale`) — plus simple et
 * fiable qu'un cookie, `detectBrowserLanguage` étant désactivé dans ce
 * projet (voir nuxt.config.ts).
 */

export type ReceiptLocale = 'fr' | 'en'

interface ReceiptStrings {
  brand: string
  documentTitle: string
  receiptNumber: string
  date: string
  type: string
  amount: string
  issuedTo: string
  counterparty: string
  reference: string
  plan: string
  footer: string
  movementTypeLabels: Partial<Record<WalletMovementType, string>>
  planLabels: Record<PlanSlug, string>
}

const RECEIPT_STRINGS: Record<ReceiptLocale, ReceiptStrings> = {
  fr: {
    brand: 'WorkTogo',
    documentTitle: 'Reçu de paiement',
    receiptNumber: 'Reçu n°',
    date: 'Date',
    type: 'Type',
    amount: 'Montant',
    issuedTo: 'Émis pour',
    counterparty: 'Contrepartie',
    reference: 'Référence',
    plan: 'Formule',
    footer: 'Reçu généré automatiquement par WorkTogo — document interne, ne constitue pas une facture fiscale.',
    movementTypeLabels: {
      escrow_debit: 'Paiement en séquestre',
      escrow_release: 'Libération de séquestre',
    },
    planLabels: {
      mensuel: 'Formule mensuelle',
      trimestriel: 'Formule trimestrielle',
      annuel: 'Formule annuelle',
    },
  },
  en: {
    brand: 'WorkTogo',
    documentTitle: 'Payment receipt',
    receiptNumber: 'Receipt #',
    date: 'Date',
    type: 'Type',
    amount: 'Amount',
    issuedTo: 'Issued to',
    counterparty: 'Counterparty',
    reference: 'Reference',
    plan: 'Plan',
    footer: 'Receipt automatically generated by WorkTogo — internal document, not a tax invoice.',
    movementTypeLabels: {
      escrow_debit: 'Escrow payment',
      escrow_release: 'Escrow release',
    },
    planLabels: {
      mensuel: 'Monthly plan',
      trimestriel: 'Quarterly plan',
      annuel: 'Annual plan',
    },
  },
}

function generatePdfBuffer(draw: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 })
    const chunks: Buffer[] = []
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
    draw(doc)
    doc.end()
  })
}

function fullName(user: User): string {
  return `${user.firstName} ${user.lastName}`.trim() || user.username
}

function drawHeader(doc: PDFKit.PDFDocument, strings: ReceiptStrings, receiptId: string) {
  doc.font('Helvetica-Bold').fontSize(20).fillColor('#14a800').text(strings.brand)
  doc.moveDown(0.3)
  doc.font('Helvetica-Bold').fontSize(14).fillColor('#111').text(strings.documentTitle)
  doc.font('Helvetica').fontSize(9).fillColor('#666').text(`${strings.receiptNumber} ${receiptId.slice(0, 12)}`)
  doc.moveDown(1.2)
  doc.strokeColor('#e5e5e5').moveTo(50, doc.y).lineTo(545, doc.y).stroke()
  doc.moveDown(1)
}

function drawRow(doc: PDFKit.PDFDocument, label: string, value: string) {
  const y = doc.y
  doc.font('Helvetica').fontSize(10).fillColor('#666').text(label, 50, y, { width: 150 })
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#111').text(value, 200, y, { width: 345 })
  doc.moveDown(0.6)
}

function drawFooter(doc: PDFKit.PDFDocument, strings: ReceiptStrings) {
  doc.moveDown(1.5)
  doc.strokeColor('#e5e5e5').moveTo(50, doc.y).lineTo(545, doc.y).stroke()
  doc.moveDown(0.8)
  doc.font('Helvetica').fontSize(8).fillColor('#999').text(strings.footer)
}

function formatDate(timestamp: number, locale: ReceiptLocale): string {
  return new Date(timestamp).toLocaleString(locale === 'en' ? 'en-US' : 'fr-FR', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function formatAmount(amount: number, locale: ReceiptLocale): string {
  return `${amount.toLocaleString(locale === 'en' ? 'en-US' : 'fr-FR')} F CFA`
}

export async function generateMovementReceiptPdf(
  movement: WalletMovement,
  owner: User,
  counterparty: User | null,
  locale: ReceiptLocale,
): Promise<Buffer> {
  const strings = RECEIPT_STRINGS[locale]
  const typeLabel = strings.movementTypeLabels[movement.type] ?? movement.type

  return generatePdfBuffer((doc) => {
    drawHeader(doc, strings, movement.id)
    drawRow(doc, strings.date, formatDate(movement.createdAt, locale))
    drawRow(doc, strings.type, typeLabel)
    drawRow(doc, strings.amount, formatAmount(movement.amount, locale))
    drawRow(doc, strings.issuedTo, fullName(owner))
    if (counterparty) drawRow(doc, strings.counterparty, fullName(counterparty))
    drawRow(doc, strings.reference, movement.reference)
    drawFooter(doc, strings)
  })
}

export async function generatePaymentReceiptPdf(
  payment: Payment,
  owner: User,
  plan: PlanSlug,
  locale: ReceiptLocale,
): Promise<Buffer> {
  const strings = RECEIPT_STRINGS[locale]

  return generatePdfBuffer((doc) => {
    drawHeader(doc, strings, payment.id)
    drawRow(doc, strings.date, formatDate(payment.resolvedAt ?? payment.createdAt, locale))
    drawRow(doc, strings.plan, strings.planLabels[plan])
    drawRow(doc, strings.amount, formatAmount(payment.amount, locale))
    drawRow(doc, strings.issuedTo, fullName(owner))
    drawRow(doc, strings.reference, payment.operatorRef ?? payment.id)
    drawFooter(doc, strings)
  })
}

export function receiptLocaleFromQuery(queryValue: unknown): ReceiptLocale {
  return queryValue === 'en' ? 'en' : 'fr'
}
